### PR TITLE
Changes to sponsor,judges,tracks

### PR DESCRIPTION
**Pull request by arushivii**
Temporary stuff done. Don't know why that shows as bhavya.

### CODE REVIEW

**Comment by arushivii** [comment]
@rexagod

**Comment by rexagod** [comment]
@av-00 Can we use a better resolution image for judges?

**Comment by arushivii** [comment]
> @av-00 Can we use a better resolution image for judges?

Can it be just an image without "to be announced" written on it?

**Comment by rexagod** [comment]
Sure. But it should nonetheless indicate that, implicitly.

**Comment by weirdwiz** [comment]
I guess we just need 1 TBA for judge, and reduce the image size

**Pull request closed without merging**
