### PR TITLE
add title favicon

### PR DESCRIPTION
**Pull request by Ankurk99**
Fixes:

### CODE REVIEW

**Comment by karandevtyagi** [comment]
@Ankurk99  I cannot preview the change.Check the logs.

**Comment by Ankurk99** [comment]
@karandevtyagi Sorry but I can't fix this, it might be a problem with netlify.

**Comment by rexagod** [comment]
It is a problem with netlify, probably maintenance. Try `git commit -m -S "trigger jobs" --allow-empty` to push an empty commit here and re-trigger these jobs.

**Comment by rexagod** [comment]
Remove the `-S` flag if you don't have a key to sign with.

**Comment by karandevtyagi** [comment]
My mistake, should have mentioned it .I was asking to check netlify deploy logs for the issue.

**Comment by Ankurk99** [comment]
Done

**Pull request merged**
