### PR TITLE
create MIT license

### LINKED ISSUE #17: Create LICENSE.md (MIT/GPLv3)

### PR DESCRIPTION
**Pull request by Ankurk99**
Fixes: #17

### CODE REVIEW

**Comment by rexagod** [comment]
ping @Ankurk99

**Comment by Ankurk99** [comment]
on it.

**Comment by rexagod** [comment]
:fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire:

**Comment by Ankurk99** [comment]
@rexagod done.

**Pull request merged**
